// AUTO-GENERATED – migrate.py
// 163 ürün

export interface ProductData {
  id: string;
  slug: string;
  name: Record<string, string>;
  categorySlug: string;
  categoryName: Record<string, string>;
  description: Record<string, string>;
  image: string;
  images?: string[];
  badge?: string;
}

export const ALL_PRODUCTS: ProductData[] = [
  {
    id: "p-4196",
    slug: "regalia-sandalye",
    name: { tr: "Regalia Sandalye", en: "Regalia Sandalye", de: "Regalia Sandalye", ru: "Regalia Sandalye", ar: "Regalia Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4200",
    slug: "valor-sandalye",
    name: { tr: "Valor Sandalye", en: "Valor Sandalye", de: "Valor Sandalye", ru: "Valor Sandalye", ar: "Valor Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4208",
    slug: "atlas-kanepe",
    name: { tr: "Atlas Kanepe", en: "Atlas Kanepe", de: "Atlas Kanepe", ru: "Atlas Kanepe", ar: "Atlas Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4348",
    slug: "ruby-berjer",
    name: { tr: "Ruby Berjer", en: "Ruby Berjer", de: "Ruby Berjer", ru: "Ruby Berjer", ar: "Ruby Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4354",
    slug: "pearl-kose-kanepe",
    name: { tr: "Pearl Köşe Kanepe", en: "Pearl Köşe Kanepe", de: "Pearl Köşe Kanepe", ru: "Pearl Köşe Kanepe", ar: "Pearl Köşe Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4357",
    slug: "midnight-kose-kanepe",
    name: { tr: "Midnight Köşe Kanepe", en: "Midnight Köşe Kanepe", de: "Midnight Köşe Kanepe", ru: "Midnight Köşe Kanepe", ar: "Midnight Köşe Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4360",
    slug: "cognac-sandalye",
    name: { tr: "Cognac Sandalye", en: "Cognac Sandalye", de: "Cognac Sandalye", ru: "Cognac Sandalye", ar: "Cognac Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4365",
    slug: "crown-sandalye",
    name: { tr: "Crown Sandalye", en: "Crown Sandalye", de: "Crown Sandalye", ru: "Crown Sandalye", ar: "Crown Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4372",
    slug: "bianca-bar-sandalye",
    name: { tr: "Bianca Bar Sandalye", en: "Bianca Bar Sandalye", de: "Bianca Bar Sandalye", ru: "Bianca Bar Sandalye", ar: "Bianca Bar Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4377",
    slug: "ritz-bar-sandalye",
    name: { tr: "Ritz Bar Sandalye", en: "Ritz Bar Sandalye", de: "Ritz Bar Sandalye", ru: "Ritz Bar Sandalye", ar: "Ritz Bar Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4381",
    slug: "aurora-kanepe",
    name: { tr: "Aurora Kanepe", en: "Aurora Kanepe", de: "Aurora Kanepe", ru: "Aurora Kanepe", ar: "Aurora Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4386",
    slug: "monroe-berjer",
    name: { tr: "Monroe Berjer", en: "Monroe Berjer", de: "Monroe Berjer", ru: "Monroe Berjer", ar: "Monroe Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4390",
    slug: "paradiso-berjer",
    name: { tr: "Paradiso Berjer", en: "Paradiso Berjer", de: "Paradiso Berjer", ru: "Paradiso Berjer", ar: "Paradiso Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4397",
    slug: "mira-bench",
    name: { tr: "Mira Bench", en: "Mira Bench", de: "Mira Bench", ru: "Mira Bench", ar: "Mira Bench" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4399",
    slug: "lora-bench",
    name: { tr: "Lora Bench", en: "Lora Bench", de: "Lora Bench", ru: "Lora Bench", ar: "Lora Bench" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4430",
    slug: "bellagio-sandalye",
    name: { tr: "Bellagio Sandalye", en: "Bellagio Sandalye", de: "Bellagio Sandalye", ru: "Bellagio Sandalye", ar: "Bellagio Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-4726",
    slug: "armoni-design",
    name: { tr: "Armoni Design", en: "Armoni Design", de: "Armoni Design", ru: "Armoni Design", ar: "Armoni Design" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-aeris-fasulye-kanepe",
    slug: "aeris-fasulye-kanepe",
    name: { tr: "Aerıs Fasulye Kanepe", en: "Aerıs Fasulye Kanepe", de: "Aerıs Fasulye Kanepe", ru: "Aerıs Fasulye Kanepe", ar: "Aerıs Fasulye Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-arc-berjer",
    slug: "arc-berjer",
    name: { tr: "Arc Berjer", en: "Arc Berjer", de: "Arc Berjer", ru: "Arc Berjer", ar: "Arc Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-arc-sandalye",
    slug: "arc-sandalye",
    name: { tr: "Arc Sandalye", en: "Arc Sandalye", de: "Arc Sandalye", ru: "Arc Sandalye", ar: "Arc Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-arco-kose-kanepe",
    slug: "arco-kose-kanepe",
    name: { tr: "Arco Köşe Kanepe", en: "Arco Köşe Kanepe", de: "Arco Köşe Kanepe", ru: "Arco Köşe Kanepe", ar: "Arco Köşe Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-arezzo-sandalye",
    slug: "arezzo-sandalye",
    name: { tr: "Arezzo Sandalye", en: "Arezzo Sandalye", de: "Arezzo Sandalye", ru: "Arezzo Sandalye", ar: "Arezzo Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-aria-bench",
    slug: "aria-bench",
    name: { tr: "Aria Bench", en: "Aria Bench", de: "Aria Bench", ru: "Aria Bench", ar: "Aria Bench" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-aston-sandalye",
    slug: "aston-sandalye",
    name: { tr: "Aston Sandalye", en: "Aston Sandalye", de: "Aston Sandalye", ru: "Aston Sandalye", ar: "Aston Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-atelier-sandalye",
    slug: "valmont-sandalye",
    name: { tr: "Valmont Sandalye", en: "Valmont Sandalye", de: "Valmont Sandalye", ru: "Valmont Sandalye", ar: "Valmont Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-atria-sandalye",
    slug: "atria-sandalye",
    name: { tr: "Atria Sandalye", en: "Atria Sandalye", de: "Atria Sandalye", ru: "Atria Sandalye", ar: "Atria Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-avela-berjer",
    slug: "avela-berjer",
    name: { tr: "Avela Berjer", en: "Avela Berjer", de: "Avela Berjer", ru: "Avela Berjer", ar: "Avela Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-axis-kanepe",
    slug: "axis-kanepe",
    name: { tr: "Axıs Kanepe", en: "Axıs Kanepe", de: "Axıs Kanepe", ru: "Axıs Kanepe", ar: "Axıs Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-axis-sehpali-kanepe",
    slug: "axis-kanepe-2",
    name: { tr: "Axıs Kanepe", en: "Axıs Kanepe", de: "Axıs Kanepe", ru: "Axıs Kanepe", ar: "Axıs Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-bellagio-berjer",
    slug: "bellagio-berjer",
    name: { tr: "Bellagio Berjer", en: "Bellagio Berjer", de: "Bellagio Berjer", ru: "Bellagio Berjer", ar: "Bellagio Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-bellagio-kanepe",
    slug: "bellagio-kanepe",
    name: { tr: "Bellagio Kanepe", en: "Bellagio Kanepe", de: "Bellagio Kanepe", ru: "Bellagio Kanepe", ar: "Bellagio Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-bellagio-kollu-sandalye",
    slug: "bellagio-kollu-sandalye",
    name: { tr: "Bellagio Kollu Sandalye", en: "Bellagio Kollu Sandalye", de: "Bellagio Kollu Sandalye", ru: "Bellagio Kollu Sandalye", ar: "Bellagio Kollu Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-bruno-berjer",
    slug: "bruno-berjer",
    name: { tr: "Bruno Berjer", en: "Bruno Berjer", de: "Bruno Berjer", ru: "Bruno Berjer", ar: "Bruno Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-calma-yatak",
    slug: "calma-yatak",
    name: { tr: "Calma Yatak", en: "Calma Yatak", de: "Calma Yatak", ru: "Calma Yatak", ar: "Calma Yatak" },
    categorySlug: "tum-urunler",
    categoryName: { tr: "Tüm Ürünler", en: "Tüm Ürünler", de: "Tüm Ürünler", ru: "Tüm Ürünler", ar: "Tüm Ürünler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-calme-berjer",
    slug: "calme-berjer",
    name: { tr: "Calme Berjer", en: "Calme Berjer", de: "Calme Berjer", ru: "Calme Berjer", ar: "Calme Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-calyx-fasulye-kanepe",
    slug: "calyx-fasulye-kanepe",
    name: { tr: "Calyx Fasulye Kanepe", en: "Calyx Fasulye Kanepe", de: "Calyx Fasulye Kanepe", ru: "Calyx Fasulye Kanepe", ar: "Calyx Fasulye Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-cheester-berjer-orjinal-deri",
    slug: "cheester-berjer",
    name: { tr: "Cheester Berjer", en: "Cheester Berjer", de: "Cheester Berjer", ru: "Cheester Berjer", ar: "Cheester Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-cheester-kanepe",
    slug: "kensington-chester-kanepe",
    name: { tr: "Kensington Chester Kanepe", en: "Kensington Chester Kanepe", de: "Kensington Chester Kanepe", ru: "Kensington Chester Kanepe", ar: "Kensington Chester Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-cleo-berjer",
    slug: "cleo-berjer",
    name: { tr: "Cleo Berjer", en: "Cleo Berjer", de: "Cleo Berjer", ru: "Cleo Berjer", ar: "Cleo Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-cloud-kanepe",
    slug: "cloud-kanepe",
    name: { tr: "Cloud Kanepe", en: "Cloud Kanepe", de: "Cloud Kanepe", ru: "Cloud Kanepe", ar: "Cloud Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-contour-berjer",
    slug: "contour-berjer",
    name: { tr: "Contour Berjer", en: "Contour Berjer", de: "Contour Berjer", ru: "Contour Berjer", ar: "Contour Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-cora-sandalye",
    slug: "cora-sandalye",
    name: { tr: "Cora Sandalye", en: "Cora Sandalye", de: "Cora Sandalye", ru: "Cora Sandalye", ar: "Cora Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-crescent-sandalye",
    slug: "crescent-sandalye",
    name: { tr: "Crescent Sandalye", en: "Crescent Sandalye", de: "Crescent Sandalye", ru: "Crescent Sandalye", ar: "Crescent Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-curve-fasulye-kanepe",
    slug: "curve-fasulye-kanepe",
    name: { tr: "Curve Fasulye Kanepe", en: "Curve Fasulye Kanepe", de: "Curve Fasulye Kanepe", ru: "Curve Fasulye Kanepe", ar: "Curve Fasulye Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-darkon-yatak",
    slug: "darkon-yatak",
    name: { tr: "Darkon Yatak", en: "Darkon Yatak", de: "Darkon Yatak", ru: "Darkon Yatak", ar: "Darkon Yatak" },
    categorySlug: "tum-urunler",
    categoryName: { tr: "Tüm Ürünler", en: "Tüm Ürünler", de: "Tüm Ürünler", ru: "Tüm Ürünler", ar: "Tüm Ürünler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-duo-berjer",
    slug: "duo-berjer",
    name: { tr: "Duo Berjer", en: "Duo Berjer", de: "Duo Berjer", ru: "Duo Berjer", ar: "Duo Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-eclipse-daybed",
    slug: "eclipse-daybed",
    name: { tr: "Eclipse Daybed", en: "Eclipse Daybed", de: "Eclipse Daybed", ru: "Eclipse Daybed", ar: "Eclipse Daybed" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-eden-berjer",
    slug: "eden-berjer",
    name: { tr: "Eden Berjer", en: "Eden Berjer", de: "Eden Berjer", ru: "Eden Berjer", ar: "Eden Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-elara-kanepe",
    slug: "elara-kanepe",
    name: { tr: "Elara Kanepe", en: "Elara Kanepe", de: "Elara Kanepe", ru: "Elara Kanepe", ar: "Elara Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-elegance",
    slug: "elegance-kanepe",
    name: { tr: "Elegance Kanepe", en: "Elegance Kanepe", de: "Elegance Kanepe", ru: "Elegance Kanepe", ar: "Elegance Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-elegance-berjer",
    slug: "elegance-berjer",
    name: { tr: "Elegance Berjer", en: "Elegance Berjer", de: "Elegance Berjer", ru: "Elegance Berjer", ar: "Elegance Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-ellipse-sandalye",
    slug: "ellipse-sandalye",
    name: { tr: "Ellipse Sandalye", en: "Ellipse Sandalye", de: "Ellipse Sandalye", ru: "Ellipse Sandalye", ar: "Ellipse Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-ember-kanepe",
    slug: "ember-kanepe",
    name: { tr: "Ember Kanepe", en: "Ember Kanepe", de: "Ember Kanepe", ru: "Ember Kanepe", ar: "Ember Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-ember-kose-kanepe",
    slug: "ember-kose-kanepe",
    name: { tr: "Ember Köşe Kanepe", en: "Ember Köşe Kanepe", de: "Ember Köşe Kanepe", ru: "Ember Köşe Kanepe", ar: "Ember Köşe Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-evoke-berjer",
    slug: "evoke-berjer",
    name: { tr: "Evoke Berjer", en: "Evoke Berjer", de: "Evoke Berjer", ru: "Evoke Berjer", ar: "Evoke Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-fjord-berjer",
    slug: "fjord-berjer",
    name: { tr: "Fjord Berjer", en: "Fjord Berjer", de: "Fjord Berjer", ru: "Fjord Berjer", ar: "Fjord Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-form-berjer",
    slug: "form-berjer",
    name: { tr: "Form Berjer", en: "Form Berjer", de: "Form Berjer", ru: "Form Berjer", ar: "Form Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-frame-sandalye",
    slug: "frame-sandalye",
    name: { tr: "Frame Sandalye", en: "Frame Sandalye", de: "Frame Sandalye", ru: "Frame Sandalye", ar: "Frame Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-granda-berjer",
    slug: "granda-berjer",
    name: { tr: "Granda Berjer", en: "Granda Berjer", de: "Granda Berjer", ru: "Granda Berjer", ar: "Granda Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-harper-berjer",
    slug: "harper-berjer",
    name: { tr: "Harper Berjer", en: "Harper Berjer", de: "Harper Berjer", ru: "Harper Berjer", ar: "Harper Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-hudson-sandalye",
    slug: "hudson-sandalye",
    name: { tr: "Hudson Sandalye", en: "Hudson Sandalye", de: "Hudson Sandalye", ru: "Hudson Sandalye", ar: "Hudson Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-isola-kanepe",
    slug: "isola-kanepe",
    name: { tr: "Isola Kanepe", en: "Isola Kanepe", de: "Isola Kanepe", ru: "Isola Kanepe", ar: "Isola Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-ivory-sandalye",
    slug: "ivory-sandalye",
    name: { tr: "Ivory Sandalye", en: "Ivory Sandalye", de: "Ivory Sandalye", ru: "Ivory Sandalye", ar: "Ivory Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-kaizen-sandalye",
    slug: "kaizen-sandalye",
    name: { tr: "Kaizen Sandalye", en: "Kaizen Sandalye", de: "Kaizen Sandalye", ru: "Kaizen Sandalye", ar: "Kaizen Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-kyoto-bar-sandalyesi",
    slug: "kyoto-bar-sandalyesi",
    name: { tr: "Kyoto Bar Sandalyesi", en: "Kyoto Bar Sandalyesi", de: "Kyoto Bar Sandalyesi", ru: "Kyoto Bar Sandalyesi", ar: "Kyoto Bar Sandalyesi" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-lagos-kose-kanepe",
    slug: "lagos-kose-kanepe",
    name: { tr: "Lagos Köşe Kanepe", en: "Lagos Köşe Kanepe", de: "Lagos Köşe Kanepe", ru: "Lagos Köşe Kanepe", ar: "Lagos Köşe Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-lento-berjer",
    slug: "lento-berjer",
    name: { tr: "Lento Berjer", en: "Lento Berjer", de: "Lento Berjer", ru: "Lento Berjer", ar: "Lento Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-linea-kanepe",
    slug: "linea-kanepe",
    name: { tr: "Lınea Kanepe", en: "Lınea Kanepe", de: "Lınea Kanepe", ru: "Lınea Kanepe", ar: "Lınea Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-liora-berjer",
    slug: "liora-berjer",
    name: { tr: "Liora Berjer", en: "Liora Berjer", de: "Liora Berjer", ru: "Liora Berjer", ar: "Liora Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-livia-sandalye",
    slug: "livia-sandalye",
    name: { tr: "Livia Sandalye", en: "Livia Sandalye", de: "Livia Sandalye", ru: "Livia Sandalye", ar: "Livia Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-livorno-kanepe",
    slug: "livorno-kanepe",
    name: { tr: "Livorno Kanepe", en: "Livorno Kanepe", de: "Livorno Kanepe", ru: "Livorno Kanepe", ar: "Livorno Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-loop-berjer",
    slug: "loop-berjer",
    name: { tr: "Loop Berjer", en: "Loop Berjer", de: "Loop Berjer", ru: "Loop Berjer", ar: "Loop Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-loren-berjer",
    slug: "loren-berjer",
    name: { tr: "Loren Berjer", en: "Loren Berjer", de: "Loren Berjer", ru: "Loren Berjer", ar: "Loren Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-lorenza-sandalye",
    slug: "lorenza-sandalye",
    name: { tr: "Lorenza Sandalye", en: "Lorenza Sandalye", de: "Lorenza Sandalye", ru: "Lorenza Sandalye", ar: "Lorenza Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-lorenzo-bar-sandalyesi",
    slug: "lorenzo-bar-sandalyesi",
    name: { tr: "Lorenzo Bar Sandalyesi", en: "Lorenzo Bar Sandalyesi", de: "Lorenzo Bar Sandalyesi", ru: "Lorenzo Bar Sandalyesi", ar: "Lorenzo Bar Sandalyesi" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-lucca-sandalye",
    slug: "lucca-sandalye",
    name: { tr: "Lucca Sandalye", en: "Lucca Sandalye", de: "Lucca Sandalye", ru: "Lucca Sandalye", ar: "Lucca Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-lucen-sandalye",
    slug: "lucen-sandalye",
    name: { tr: "Lucen Sandalye", en: "Lucen Sandalye", de: "Lucen Sandalye", ru: "Lucen Sandalye", ar: "Lucen Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-lugano-kanepe",
    slug: "lugano-kanepe",
    name: { tr: "Lugano Kanepe", en: "Lugano Kanepe", de: "Lugano Kanepe", ru: "Lugano Kanepe", ar: "Lugano Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-lume-sehpali-kanepe",
    slug: "lume-sehpali-kanepe",
    name: { tr: "Lume Sehpalı Kanepe", en: "Lume Sehpalı Kanepe", de: "Lume Sehpalı Kanepe", ru: "Lume Sehpalı Kanepe", ar: "Lume Sehpalı Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-lumera-yatak",
    slug: "lumera-yatak",
    name: { tr: "Lumera Yatak", en: "Lumera Yatak", de: "Lumera Yatak", ru: "Lumera Yatak", ar: "Lumera Yatak" },
    categorySlug: "tum-urunler",
    categoryName: { tr: "Tüm Ürünler", en: "Tüm Ürünler", de: "Tüm Ürünler", ru: "Tüm Ürünler", ar: "Tüm Ürünler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-luna-kanepe",
    slug: "luna-kanepe",
    name: { tr: "Luna Kanepe", en: "Luna Kanepe", de: "Luna Kanepe", ru: "Luna Kanepe", ar: "Luna Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-luxon-yatak",
    slug: "luxon-yatak",
    name: { tr: "Luxon Yatak", en: "Luxon Yatak", de: "Luxon Yatak", ru: "Luxon Yatak", ar: "Luxon Yatak" },
    categorySlug: "yatak-odasi",
    categoryName: { tr: "Yatak Odası", en: "Yatak Odası", de: "Yatak Odası", ru: "Yatak Odası", ar: "Yatak Odası" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-luxor-kose-kanepe",
    slug: "luxor-kose-kanepe",
    name: { tr: "Luxor Köşe Kanepe", en: "Luxor Köşe Kanepe", de: "Luxor Köşe Kanepe", ru: "Luxor Köşe Kanepe", ar: "Luxor Köşe Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-lyra-bench",
    slug: "lyra-bench",
    name: { tr: "Lyra Bench", en: "Lyra Bench", de: "Lyra Bench", ru: "Lyra Bench", ar: "Lyra Bench" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-maren-fasulye-kanepe",
    slug: "maren-fasulye-kanepe",
    name: { tr: "Maren Fasulye Kanepe", en: "Maren Fasulye Kanepe", de: "Maren Fasulye Kanepe", ru: "Maren Fasulye Kanepe", ar: "Maren Fasulye Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-marlow-sandalye",
    slug: "marlow-sandalye",
    name: { tr: "Marlow Sandalye", en: "Marlow Sandalye", de: "Marlow Sandalye", ru: "Marlow Sandalye", ar: "Marlow Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-matera-berjer",
    slug: "matera-berjer",
    name: { tr: "Matera Berjer", en: "Matera Berjer", de: "Matera Berjer", ru: "Matera Berjer", ar: "Matera Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-maverick-berjer",
    slug: "maverick-berjer",
    name: { tr: "Maverick Berjer", en: "Maverick Berjer", de: "Maverick Berjer", ru: "Maverick Berjer", ar: "Maverick Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-mayfair-berjer",
    slug: "mayfair-berjer",
    name: { tr: "Mayfair Berjer", en: "Mayfair Berjer", de: "Mayfair Berjer", ru: "Mayfair Berjer", ar: "Mayfair Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-mediterraneo-sedir",
    slug: "mediterraneo-sedir",
    name: { tr: "Mediterraneo Sedir", en: "Mediterraneo Sedir", de: "Mediterraneo Sedir", ru: "Mediterraneo Sedir", ar: "Mediterraneo Sedir" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-mila-sandalye",
    slug: "mila-sandalye",
    name: { tr: "Mila Sandalye", en: "Mila Sandalye", de: "Mila Sandalye", ru: "Mila Sandalye", ar: "Mila Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-milan-berjer",
    slug: "milan-berjer",
    name: { tr: "Milan Berjer", en: "Milan Berjer", de: "Milan Berjer", ru: "Milan Berjer", ar: "Milan Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-milo-berjer",
    slug: "milo-berjer",
    name: { tr: "Milo Berjer", en: "Milo Berjer", de: "Milo Berjer", ru: "Milo Berjer", ar: "Milo Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-minotti-berjer-2",
    slug: "ruby-berjer-kanepe-takimi",
    name: { tr: "Ruby Berjer & Kanepe Takımı", en: "Ruby Berjer & Kanepe Takımı", de: "Ruby Berjer & Kanepe Takımı", ru: "Ruby Berjer & Kanepe Takımı", ar: "Ruby Berjer & Kanepe Takımı" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-mono-kanepe",
    slug: "mono-kanepe",
    name: { tr: "Mono Kanepe", en: "Mono Kanepe", de: "Mono Kanepe", ru: "Mono Kanepe", ar: "Mono Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-monolith-sandalye",
    slug: "monolith-sandalye",
    name: { tr: "Monolith Sandalye", en: "Monolith Sandalye", de: "Monolith Sandalye", ru: "Monolith Sandalye", ar: "Monolith Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-montera-kose-kanepe",
    slug: "montera-kose-kanepe",
    name: { tr: "Montera Köşe Kanepe", en: "Montera Köşe Kanepe", de: "Montera Köşe Kanepe", ru: "Montera Köşe Kanepe", ar: "Montera Köşe Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-mora-sandalye",
    slug: "mora-sandalye",
    name: { tr: "Mora Sandalye", en: "Mora Sandalye", de: "Mora Sandalye", ru: "Mora Sandalye", ar: "Mora Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-mosaic-kanepe",
    slug: "mosaic-kanepe",
    name: { tr: "Mosaic Kanepe", en: "Mosaic Kanepe", de: "Mosaic Kanepe", ru: "Mosaic Kanepe", ar: "Mosaic Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-muse-berjer",
    slug: "nara-berjer",
    name: { tr: "Nara Berjer", en: "Nara Berjer", de: "Nara Berjer", ru: "Nara Berjer", ar: "Nara Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-nabu-sandalye",
    slug: "nabu-sandalye",
    name: { tr: "Nabu Sandalye", en: "Nabu Sandalye", de: "Nabu Sandalye", ru: "Nabu Sandalye", ar: "Nabu Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-nacre-kose-kanepe",
    slug: "nacre-kose-kanepe",
    name: { tr: "Nacre Köşe Kanepe", en: "Nacre Köşe Kanepe", de: "Nacre Köşe Kanepe", ru: "Nacre Köşe Kanepe", ar: "Nacre Köşe Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-natura-yatak",
    slug: "natura-yatak",
    name: { tr: "Natura Yatak", en: "Natura Yatak", de: "Natura Yatak", ru: "Natura Yatak", ar: "Natura Yatak" },
    categorySlug: "tum-urunler",
    categoryName: { tr: "Tüm Ürünler", en: "Tüm Ürünler", de: "Tüm Ürünler", ru: "Tüm Ürünler", ar: "Tüm Ürünler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-nautica-berjer",
    slug: "nautica-berjer",
    name: { tr: "Nautica Berjer", en: "Nautica Berjer", de: "Nautica Berjer", ru: "Nautica Berjer", ar: "Nautica Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-nero-berjer",
    slug: "nero-berjer",
    name: { tr: "Nero Berjer", en: "Nero Berjer", de: "Nero Berjer", ru: "Nero Berjer", ar: "Nero Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-noble-berjer",
    slug: "noble-berjer",
    name: { tr: "Noble Berjer", en: "Noble Berjer", de: "Noble Berjer", ru: "Noble Berjer", ar: "Noble Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-noir-kanepe",
    slug: "noir-kanepe",
    name: { tr: "Noır Kanepe", en: "Noır Kanepe", de: "Noır Kanepe", ru: "Noır Kanepe", ar: "Noır Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-noma-berjer",
    slug: "noma-berjer",
    name: { tr: "Noma Berjer", en: "Noma Berjer", de: "Noma Berjer", ru: "Noma Berjer", ar: "Noma Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-noma-kanepe",
    slug: "noma-kanepe",
    name: { tr: "Noma Kanepe", en: "Noma Kanepe", de: "Noma Kanepe", ru: "Noma Kanepe", ar: "Noma Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-nomad-modul-kanepe",
    slug: "nomad-modul-kanepe",
    name: { tr: "Nomad Modül Kanepe", en: "Nomad Modül Kanepe", de: "Nomad Modül Kanepe", ru: "Nomad Modül Kanepe", ar: "Nomad Modül Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-nomad-modul-kanepe-2",
    slug: "nomad-modul-kanepe-2",
    name: { tr: "Nomad Modül Kanepe", en: "Nomad Modül Kanepe", de: "Nomad Modül Kanepe", ru: "Nomad Modül Kanepe", ar: "Nomad Modül Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-nord-sandalye",
    slug: "nord-sandalye",
    name: { tr: "Nord Sandalye", en: "Nord Sandalye", de: "Nord Sandalye", ru: "Nord Sandalye", ar: "Nord Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-nox-kanepe",
    slug: "nox-kanepe",
    name: { tr: "Nox Kanepe", en: "Nox Kanepe", de: "Nox Kanepe", ru: "Nox Kanepe", ar: "Nox Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-oblio-sandalye",
    slug: "oblio-sandalye",
    name: { tr: "Oblio Sandalye", en: "Oblio Sandalye", de: "Oblio Sandalye", ru: "Oblio Sandalye", ar: "Oblio Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-oliva-kanepe",
    slug: "oliva-kanepe",
    name: { tr: "Olıva Kanepe", en: "Olıva Kanepe", de: "Olıva Kanepe", ru: "Olıva Kanepe", ar: "Olıva Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-opaline-berjer",
    slug: "opaline-berjer",
    name: { tr: "Opaline Berjer", en: "Opaline Berjer", de: "Opaline Berjer", ru: "Opaline Berjer", ar: "Opaline Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-ora-bar-sandalyesi",
    slug: "ora-bar-sandalyesi",
    name: { tr: "Ora Bar Sandalyesi", en: "Ora Bar Sandalyesi", de: "Ora Bar Sandalyesi", ru: "Ora Bar Sandalyesi", ar: "Ora Bar Sandalyesi" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-orbit-kanepe",
    slug: "orbit-kanepe",
    name: { tr: "Orbıt Kanepe", en: "Orbıt Kanepe", de: "Orbıt Kanepe", ru: "Orbıt Kanepe", ar: "Orbıt Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-palazzo-berjer",
    slug: "palazzo-berjer",
    name: { tr: "Palazzo Berjer", en: "Palazzo Berjer", de: "Palazzo Berjer", ru: "Palazzo Berjer", ar: "Palazzo Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-parma-berjer",
    slug: "parma-berjer",
    name: { tr: "Parma Berjer", en: "Parma Berjer", de: "Parma Berjer", ru: "Parma Berjer", ar: "Parma Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-pattern-berjer",
    slug: "pattern-berjer",
    name: { tr: "Pattern Berjer", en: "Pattern Berjer", de: "Pattern Berjer", ru: "Pattern Berjer", ar: "Pattern Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-pearl-sandalye",
    slug: "pearl-sandalye",
    name: { tr: "Pearl Sandalye", en: "Pearl Sandalye", de: "Pearl Sandalye", ru: "Pearl Sandalye", ar: "Pearl Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-pebble-berjer",
    slug: "pebble-berjer",
    name: { tr: "Pebble Berjer", en: "Pebble Berjer", de: "Pebble Berjer", ru: "Pebble Berjer", ar: "Pebble Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-porto-kanepe",
    slug: "porto-kanepe",
    name: { tr: "Porto Kanepe", en: "Porto Kanepe", de: "Porto Kanepe", ru: "Porto Kanepe", ar: "Porto Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-portofino-berjer",
    slug: "portofino-berjer",
    name: { tr: "Portofino Berjer", en: "Portofino Berjer", de: "Portofino Berjer", ru: "Portofino Berjer", ar: "Portofino Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-positano-kose-kanepe",
    slug: "positano-kose-kanepe",
    name: { tr: "Positano Köşe Kanepe", en: "Positano Köşe Kanepe", de: "Positano Köşe Kanepe", ru: "Positano Köşe Kanepe", ar: "Positano Köşe Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-ravello-sandalye",
    slug: "ravello-sandalye",
    name: { tr: "Ravello Sandalye", en: "Ravello Sandalye", de: "Ravello Sandalye", ru: "Ravello Sandalye", ar: "Ravello Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-ravenna-kose-kanepe",
    slug: "ravenna-kose-kanepe",
    name: { tr: "Ravenna Köşe Kanepe", en: "Ravenna Köşe Kanepe", de: "Ravenna Köşe Kanepe", ru: "Ravenna Köşe Kanepe", ar: "Ravenna Köşe Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-regent-kanepe",
    slug: "regent-kanepe",
    name: { tr: "Regent Kanepe", en: "Regent Kanepe", de: "Regent Kanepe", ru: "Regent Kanepe", ar: "Regent Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-rialto-sandalye",
    slug: "rialto-sandalye",
    name: { tr: "Rialto Sandalye", en: "Rialto Sandalye", de: "Rialto Sandalye", ru: "Rialto Sandalye", ar: "Rialto Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-root-berjer",
    slug: "root-berjer",
    name: { tr: "Root Berjer", en: "Root Berjer", de: "Root Berjer", ru: "Root Berjer", ar: "Root Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-rossi-sandalye",
    slug: "rossi-sandalye",
    name: { tr: "Rossi Sandalye", en: "Rossi Sandalye", de: "Rossi Sandalye", ru: "Rossi Sandalye", ar: "Rossi Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-ruby-kollu-berjer",
    slug: "ruby-kollu-berjer",
    name: { tr: "Ruby Kollu Berjer", en: "Ruby Kollu Berjer", de: "Ruby Kollu Berjer", ru: "Ruby Kollu Berjer", ar: "Ruby Kollu Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-savoy-berjer",
    slug: "savoy-berjer",
    name: { tr: "Savoy Berjer", en: "Savoy Berjer", de: "Savoy Berjer", ru: "Savoy Berjer", ar: "Savoy Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-savoy-kose-koltuk",
    slug: "savoy-kose-kanepe",
    name: { tr: "Savoy Köşe Kanepe", en: "Savoy Köşe Kanepe", de: "Savoy Köşe Kanepe", ru: "Savoy Köşe Kanepe", ar: "Savoy Köşe Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-segmenta-kanepe",
    slug: "segmenta-kanepe",
    name: { tr: "Segmenta Kanepe", en: "Segmenta Kanepe", de: "Segmenta Kanepe", ru: "Segmenta Kanepe", ar: "Segmenta Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-segmenta-yatak",
    slug: "segmenta-yatak",
    name: { tr: "Segmenta Yatak", en: "Segmenta Yatak", de: "Segmenta Yatak", ru: "Segmenta Yatak", ar: "Segmenta Yatak" },
    categorySlug: "tum-urunler",
    categoryName: { tr: "Tüm Ürünler", en: "Tüm Ürünler", de: "Tüm Ürünler", ru: "Tüm Ürünler", ar: "Tüm Ürünler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-serene-berjer",
    slug: "serene-berjer",
    name: { tr: "Serene Berjer", en: "Serene Berjer", de: "Serene Berjer", ru: "Serene Berjer", ar: "Serene Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-serenity-daybed",
    slug: "serenity-daybed",
    name: { tr: "Serenity Daybed", en: "Serenity Daybed", de: "Serenity Daybed", ru: "Serenity Daybed", ar: "Serenity Daybed" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-siena-berjer",
    slug: "siena-berjer",
    name: { tr: "Sıena Berjer", en: "Sıena Berjer", de: "Sıena Berjer", ru: "Sıena Berjer", ar: "Sıena Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-signum-berjer",
    slug: "signum-berjer",
    name: { tr: "Sıgnum Berjer", en: "Sıgnum Berjer", de: "Sıgnum Berjer", ru: "Sıgnum Berjer", ar: "Sıgnum Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-soft-kose-kanepe",
    slug: "soft-kose-kanepe",
    name: { tr: "Soft Köşe Kanepe", en: "Soft Köşe Kanepe", de: "Soft Köşe Kanepe", ru: "Soft Köşe Kanepe", ar: "Soft Köşe Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-solis-kanepe",
    slug: "solis-kanepe",
    name: { tr: "Solıs Kanepe", en: "Solıs Kanepe", de: "Solıs Kanepe", ru: "Solıs Kanepe", ar: "Solıs Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-sorella-berjer",
    slug: "sorella-berjer",
    name: { tr: "Sorella Berjer", en: "Sorella Berjer", de: "Sorella Berjer", ru: "Sorella Berjer", ar: "Sorella Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-sorrento-sandalye",
    slug: "sorrento-sandalye",
    name: { tr: "Sorrento Sandalye", en: "Sorrento Sandalye", de: "Sorrento Sandalye", ru: "Sorrento Sandalye", ar: "Sorrento Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-sterling-sandalye",
    slug: "sterling-sandalye",
    name: { tr: "Sterling Sandalye", en: "Sterling Sandalye", de: "Sterling Sandalye", ru: "Sterling Sandalye", ar: "Sterling Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-terra-bench",
    slug: "terra-bench",
    name: { tr: "Terra Bench", en: "Terra Bench", de: "Terra Bench", ru: "Terra Bench", ar: "Terra Bench" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-terra-modul-kanepe",
    slug: "terra-kanepe",
    name: { tr: "Terra Kanepe", en: "Terra Kanepe", de: "Terra Kanepe", ru: "Terra Kanepe", ar: "Terra Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-tilia-berjer",
    slug: "tilia-berjer",
    name: { tr: "Tilia Berjer", en: "Tilia Berjer", de: "Tilia Berjer", ru: "Tilia Berjer", ar: "Tilia Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-titan-sandalye",
    slug: "titan-sandalye",
    name: { tr: "Titan Sandalye", en: "Titan Sandalye", de: "Titan Sandalye", ru: "Titan Sandalye", ar: "Titan Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-torino-kose-kanepe",
    slug: "torino-kose-kanepe",
    name: { tr: "Torino Köşe Kanepe", en: "Torino Köşe Kanepe", de: "Torino Köşe Kanepe", ru: "Torino Köşe Kanepe", ar: "Torino Köşe Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-toscana-berjer",
    slug: "toscana-berjer",
    name: { tr: "Toscana Berjer", en: "Toscana Berjer", de: "Toscana Berjer", ru: "Toscana Berjer", ar: "Toscana Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-valen-berjer",
    slug: "valen-berjer",
    name: { tr: "Valen Berjer", en: "Valen Berjer", de: "Valen Berjer", ru: "Valen Berjer", ar: "Valen Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-velia-sandalye",
    slug: "velia-sandalye",
    name: { tr: "Velia Sandalye", en: "Velia Sandalye", de: "Velia Sandalye", ru: "Velia Sandalye", ar: "Velia Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-velveta-berjer",
    slug: "velveta-berjer",
    name: { tr: "Velveta Berjer", en: "Velveta Berjer", de: "Velveta Berjer", ru: "Velveta Berjer", ar: "Velveta Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-verta-yatak",
    slug: "verta-yatak",
    name: { tr: "Verta Yatak", en: "Verta Yatak", de: "Verta Yatak", ru: "Verta Yatak", ar: "Verta Yatak" },
    categorySlug: "yatak-odasi",
    categoryName: { tr: "Yatak Odası", en: "Yatak Odası", de: "Yatak Odası", ru: "Yatak Odası", ar: "Yatak Odası" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-vesper-berjer",
    slug: "vesper-berjer",
    name: { tr: "Vesper Berjer", en: "Vesper Berjer", de: "Vesper Berjer", ru: "Vesper Berjer", ar: "Vesper Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-viona-fasulye-kanepe",
    slug: "viona-fasulye-kanepe",
    name: { tr: "Vıona Fasulye Kanepe", en: "Vıona Fasulye Kanepe", de: "Vıona Fasulye Kanepe", ru: "Vıona Fasulye Kanepe", ar: "Vıona Fasulye Kanepe" },
    categorySlug: "kanepe-kose-takimlari",
    categoryName: { tr: "Kanepe & Köşe Takımları", en: "Kanepe & Köşe Takımları", de: "Kanepe & Köşe Takımları", ru: "Kanepe & Köşe Takımları", ar: "Kanepe & Köşe Takımları" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-vittorio-sandalye",
    slug: "vittorio-sandalye",
    name: { tr: "Vittorio Sandalye", en: "Vittorio Sandalye", de: "Vittorio Sandalye", ru: "Vittorio Sandalye", ar: "Vittorio Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-walden-sandalye",
    slug: "walden-sandalye",
    name: { tr: "Walden Sandalye", en: "Walden Sandalye", de: "Walden Sandalye", ru: "Walden Sandalye", ar: "Walden Sandalye" },
    categorySlug: "sandalye-benchler",
    categoryName: { tr: "Sandalye & Benchler", en: "Sandalye & Benchler", de: "Sandalye & Benchler", ru: "Sandalye & Benchler", ar: "Sandalye & Benchler" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-weave-berjer",
    slug: "weave-berjer",
    name: { tr: "Weave Berjer", en: "Weave Berjer", de: "Weave Berjer", ru: "Weave Berjer", ar: "Weave Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-zarif-kavis-ahsap-kollu-berjer",
    slug: "marella-berjer",
    name: { tr: "Marella Berjer", en: "Marella Berjer", de: "Marella Berjer", ru: "Marella Berjer", ar: "Marella Berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
  {
    id: "p-zen-berjer",
    slug: "zen-berjer",
    name: { tr: "Zen berjer", en: "Zen berjer", de: "Zen berjer", ru: "Zen berjer", ar: "Zen berjer" },
    categorySlug: "berjer",
    categoryName: { tr: "Berjer", en: "Berjer", de: "Berjer", ru: "Berjer", ar: "Berjer" },
    description: { tr: "", en: "", de: "", ru: "", ar: "" },
    image: "/images/placeholder.jpg",
    images: [],
  },
];

export default ALL_PRODUCTS;